[project]
name = "rustshogi-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"

[dependency-groups]
dev = [
    "nox>=2025.5.1",
    "pytest>=8.3.5",
]
